- name: Install Wayland and sway
  pkgng:
    name:
      - wayland
      - seatd
      - sway
      - swayidle
      - swaylock-effects
      - lxsession
      - py39-pip
    state: present

- name: Install pywal
  pip:
    name:
      - pywal
      - pywalfox

- name: configure seatd
  command: sysrc seatd_enable="YES"

- name: start seatd
  service:
    name: seatd
    state: started