- name: Install Wayland and sway
  pkgng:
    name:
      - wayland
      - seatd
      - sway
      - swayidle
      - swaylock-effects
      - lxsession
      - py39-pip
      - shuf
      - imagemagick7
    state: present

- name: Install pywal
  pip:
    name:
      - pywal
      - pywalfox

- name: Run Pywal
  command: wal -i $(find /home/srylax/.config/sway/wallpapers/ -type f | shuf -n 1) -e

- name: Run Pywalfox
  command: pywalfox install

- name: configure seatd
  command: sysrc seatd_enable="YES"

- name: start seatd
  service:
    name: seatd
    state: started