- name: Install Applications
  community.general.pacman:
    name:
      - kitty
      - polkit-kde-agent
      - qt5-wayland
      - qt6-wayland
      - pipewire
      - wireplumber
      - dunst
      - gnome-keyring
      - libsecret
      - openssh
      - nano
      - fish
      - firefox
      - xorg-xrdb
      - thunar
      - starship
      - wofi
      - unzip
      - gtk4
      - gtk3
      - gtk2
    state: present

#- name: Install Applications with yay
#  community.general.pacman:
#    name:
#        - jetbrains-toolbox
#        - sov
#        - Hyprland
#        - wev
#        - hyprpaper-git
#        - xdg-desktop-portal-hyprland-git
#        - gtkcord4
#        - nwg-look
#    state: present
#    executable: yay
#    extra_args: --builddir /var/cache/yay

- name: SST
  include_tasks: sst.yml