- name: Install Applications
  community.general.pacman:
    name:
      - alacritty
      - nano
      - fish
      - firefox
      - xorg-xrdb
      - thunar
      - waybar
      - starship
      - wofi
      - unzip
    state: present

#- name: Install Applications with yay
#  community.general.pacman:
#    name:
#        - jetbrains-toolbox
#        - sov
#    state: present
#    executable: yay
#    extra_args: --builddir /var/cache/yay

- name: SST
  include_tasks: sst.yml