- name: Install Wayland and sway
  community.general.pacman:
    name:
      - wayland
      - sway
      - swayidle
      - swaylock
      - lxsession
      - python-setuptools
      - imagemagick
    state: present

- name: Pywal
  include_tasks: pywal.yml